# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 's.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QComboBox,
    QDialog, QHeaderView, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QSlider, QTabWidget,
    QTableWidget, QTableWidgetItem, QTextEdit, QWidget)

class Ui_Daybreak_music(object):
    def setupUi(self, Daybreak_music):
        if not Daybreak_music.objectName():
            Daybreak_music.setObjectName(u"Daybreak_music")
        Daybreak_music.resize(1325, 1162)
        Daybreak_music.setStyleSheet(u"")
        self.tabWidget = QTabWidget(Daybreak_music)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1161, 751))
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.listWidget = QTableWidget(self.tab)
        if (self.listWidget.columnCount() < 3):
            self.listWidget.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.listWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.listWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.listWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(200, 80, 811, 361))
        self.listWidget.setStyleSheet(u"")
        self.listWidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.listWidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.horizontalSlider_processbar = QSlider(self.tab)
        self.horizontalSlider_processbar.setObjectName(u"horizontalSlider_processbar")
        self.horizontalSlider_processbar.setGeometry(QRect(120, 500, 581, 21))
        self.horizontalSlider_processbar.setOrientation(Qt.Horizontal)
        self.label_pictureload = QLabel(self.tab)
        self.label_pictureload.setObjectName(u"label_pictureload")
        self.label_pictureload.setGeometry(QRect(20, 510, 81, 81))
        self.pushButton = QPushButton(self.tab)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 590, 151, 41))
        self.pushButton_nextsong = QPushButton(self.tab)
        self.pushButton_nextsong.setObjectName(u"pushButton_nextsong")
        self.pushButton_nextsong.setGeometry(QRect(530, 590, 104, 41))
        self.pushButton_beforesong = QPushButton(self.tab)
        self.pushButton_beforesong.setObjectName(u"pushButton_beforesong")
        self.pushButton_beforesong.setGeometry(QRect(310, 590, 104, 41))
        self.pushButton_playmusic = QPushButton(self.tab)
        self.pushButton_playmusic.setObjectName(u"pushButton_playmusic")
        self.pushButton_playmusic.setGeometry(QRect(420, 590, 104, 41))
        self.pushButton_playmusic.setCheckable(False)
        self.comboBox_playmode = QComboBox(self.tab)
        self.comboBox_playmode.addItem("")
        self.comboBox_playmode.addItem("")
        self.comboBox_playmode.addItem("")
        self.comboBox_playmode.addItem("")
        self.comboBox_playmode.setObjectName(u"comboBox_playmode")
        self.comboBox_playmode.setGeometry(QRect(780, 590, 131, 44))
        self.comboBox_playmode.setStyleSheet(u"")
        self.verticalSlider_setvoice = QSlider(self.tab)
        self.verticalSlider_setvoice.setObjectName(u"verticalSlider_setvoice")
        self.verticalSlider_setvoice.setGeometry(QRect(720, 500, 160, 22))
        self.verticalSlider_setvoice.setOrientation(Qt.Horizontal)
        self.checkBox_lrcshow = QCheckBox(self.tab)
        self.checkBox_lrcshow.setObjectName(u"checkBox_lrcshow")
        self.checkBox_lrcshow.setGeometry(QRect(660, 590, 101, 21))
        self.label_musicprocesstext = QLabel(self.tab)
        self.label_musicprocesstext.setObjectName(u"label_musicprocesstext")
        self.label_musicprocesstext.setGeometry(QRect(590, 520, 121, 31))
        self.label_songname = QLabel(self.tab)
        self.label_songname.setObjectName(u"label_songname")
        self.label_songname.setGeometry(QRect(30, 460, 581, 31))
        self.pushButton_localmusicsearch = QPushButton(self.tab)
        self.pushButton_localmusicsearch.setObjectName(u"pushButton_localmusicsearch")
        self.pushButton_localmusicsearch.setGeometry(QRect(10, 30, 101, 31))
        self.pushButton_internetmusicsearch = QPushButton(self.tab)
        self.pushButton_internetmusicsearch.setObjectName(u"pushButton_internetmusicsearch")
        self.pushButton_internetmusicsearch.setGeometry(QRect(10, 70, 101, 31))
        self.pushButton_settings = QPushButton(self.tab)
        self.pushButton_settings.setObjectName(u"pushButton_settings")
        self.pushButton_settings.setGeometry(QRect(10, 150, 101, 31))
        self.label_window_title_bar = QLabel(self.tab)
        self.label_window_title_bar.setObjectName(u"label_window_title_bar")
        self.label_window_title_bar.setGeometry(QRect(0, 0, 1071, 31))
        self.label_close_window = QLabel(self.tab)
        self.label_close_window.setObjectName(u"label_close_window")
        self.label_close_window.setGeometry(QRect(1110, 0, 20, 21))
        self.label_Minimize = QLabel(self.tab)
        self.label_Minimize.setObjectName(u"label_Minimize")
        self.label_Minimize.setGeometry(QRect(1080, 0, 21, 21))
        self.label_processbar_text_2 = QLabel(self.tab)
        self.label_processbar_text_2.setObjectName(u"label_processbar_text_2")
        self.label_processbar_text_2.setGeometry(QRect(120, 500, 581, 21))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_internetmusicsearch_2 = QPushButton(self.tab_2)
        self.pushButton_internetmusicsearch_2.setObjectName(u"pushButton_internetmusicsearch_2")
        self.pushButton_internetmusicsearch_2.setGeometry(QRect(10, 70, 101, 31))
        self.pushButton_localmusicsearch_2 = QPushButton(self.tab_2)
        self.pushButton_localmusicsearch_2.setObjectName(u"pushButton_localmusicsearch_2")
        self.pushButton_localmusicsearch_2.setGeometry(QRect(10, 30, 101, 31))
        self.lineEdit_163keywords = QLineEdit(self.tab_2)
        self.lineEdit_163keywords.setObjectName(u"lineEdit_163keywords")
        self.lineEdit_163keywords.setGeometry(QRect(200, 30, 811, 41))
        self.onlinesearch_tablewidget = QTableWidget(self.tab_2)
        if (self.onlinesearch_tablewidget.columnCount() < 2):
            self.onlinesearch_tablewidget.setColumnCount(2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.onlinesearch_tablewidget.setHorizontalHeaderItem(0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.onlinesearch_tablewidget.setHorizontalHeaderItem(1, __qtablewidgetitem4)
        self.onlinesearch_tablewidget.setObjectName(u"onlinesearch_tablewidget")
        self.onlinesearch_tablewidget.setGeometry(QRect(200, 80, 811, 361))
        self.onlinesearch_tablewidget.setStyleSheet(u"")
        self.onlinesearch_tablewidget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.onlinesearch_tablewidget.setSelectionMode(QAbstractItemView.SingleSelection)
        self.onlinesearch_tablewidget.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.pushButton_playmusic_2 = QPushButton(self.tab_2)
        self.pushButton_playmusic_2.setObjectName(u"pushButton_playmusic_2")
        self.pushButton_playmusic_2.setGeometry(QRect(420, 590, 104, 41))
        self.pushButton_playmusic_2.setCheckable(False)
        self.pushButton_beforesong_2 = QPushButton(self.tab_2)
        self.pushButton_beforesong_2.setObjectName(u"pushButton_beforesong_2")
        self.pushButton_beforesong_2.setGeometry(QRect(310, 590, 104, 41))
        self.pushButton_nextsong_2 = QPushButton(self.tab_2)
        self.pushButton_nextsong_2.setObjectName(u"pushButton_nextsong_2")
        self.pushButton_nextsong_2.setGeometry(QRect(530, 590, 104, 41))
        self.horizontalSlider_processbar_2 = QSlider(self.tab_2)
        self.horizontalSlider_processbar_2.setObjectName(u"horizontalSlider_processbar_2")
        self.horizontalSlider_processbar_2.setGeometry(QRect(120, 500, 581, 21))
        self.horizontalSlider_processbar_2.setOrientation(Qt.Horizontal)
        self.label_musicprocesstext_2 = QLabel(self.tab_2)
        self.label_musicprocesstext_2.setObjectName(u"label_musicprocesstext_2")
        self.label_musicprocesstext_2.setGeometry(QRect(590, 520, 121, 31))
        self.label_pictureload_2 = QLabel(self.tab_2)
        self.label_pictureload_2.setObjectName(u"label_pictureload_2")
        self.label_pictureload_2.setGeometry(QRect(20, 510, 81, 81))
        self.label_songname_2 = QLabel(self.tab_2)
        self.label_songname_2.setObjectName(u"label_songname_2")
        self.label_songname_2.setGeometry(QRect(30, 459, 571, 31))
        self.verticalSlider_setvoice_2 = QSlider(self.tab_2)
        self.verticalSlider_setvoice_2.setObjectName(u"verticalSlider_setvoice_2")
        self.verticalSlider_setvoice_2.setGeometry(QRect(720, 500, 160, 22))
        self.verticalSlider_setvoice_2.setOrientation(Qt.Horizontal)
        self.comboBox_playmode_2 = QComboBox(self.tab_2)
        self.comboBox_playmode_2.addItem("")
        self.comboBox_playmode_2.addItem("")
        self.comboBox_playmode_2.addItem("")
        self.comboBox_playmode_2.addItem("")
        self.comboBox_playmode_2.setObjectName(u"comboBox_playmode_2")
        self.comboBox_playmode_2.setGeometry(QRect(780, 590, 131, 44))
        self.comboBox_playmode_2.setStyleSheet(u"")
        self.pushButton_settings_2 = QPushButton(self.tab_2)
        self.pushButton_settings_2.setObjectName(u"pushButton_settings_2")
        self.pushButton_settings_2.setGeometry(QRect(10, 150, 101, 31))
        self.pushButton_reloadonlinemusic = QPushButton(self.tab_2)
        self.pushButton_reloadonlinemusic.setObjectName(u"pushButton_reloadonlinemusic")
        self.pushButton_reloadonlinemusic.setGeometry(QRect(140, 590, 91, 41))
        self.label_window_title_bar_3 = QLabel(self.tab_2)
        self.label_window_title_bar_3.setObjectName(u"label_window_title_bar_3")
        self.label_window_title_bar_3.setGeometry(QRect(0, 0, 1071, 31))
        self.label_close_window_2 = QLabel(self.tab_2)
        self.label_close_window_2.setObjectName(u"label_close_window_2")
        self.label_close_window_2.setGeometry(QRect(1110, 0, 21, 21))
        self.label_Minimize_2 = QLabel(self.tab_2)
        self.label_Minimize_2.setObjectName(u"label_Minimize_2")
        self.label_Minimize_2.setGeometry(QRect(1080, 0, 21, 21))
        self.label_processbar_text = QLabel(self.tab_2)
        self.label_processbar_text.setObjectName(u"label_processbar_text")
        self.label_processbar_text.setGeometry(QRect(120, 500, 581, 21))
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.pushButton_localmusicsearch_3 = QPushButton(self.tab_3)
        self.pushButton_localmusicsearch_3.setObjectName(u"pushButton_localmusicsearch_3")
        self.pushButton_localmusicsearch_3.setGeometry(QRect(10, 30, 101, 31))
        self.pushButton_internetmusicsearch_3 = QPushButton(self.tab_3)
        self.pushButton_internetmusicsearch_3.setObjectName(u"pushButton_internetmusicsearch_3")
        self.pushButton_internetmusicsearch_3.setGeometry(QRect(10, 70, 101, 31))
        self.pushButton_settings_3 = QPushButton(self.tab_3)
        self.pushButton_settings_3.setObjectName(u"pushButton_settings_3")
        self.pushButton_settings_3.setGeometry(QRect(10, 150, 101, 31))
        self.tabWidget_2 = QTabWidget(self.tab_3)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tabWidget_2.setGeometry(QRect(240, 40, 881, 611))
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label_2 = QLabel(self.tab_4)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 110, 101, 31))
        self.lineEdit_163_usercookie = QLineEdit(self.tab_4)
        self.lineEdit_163_usercookie.setObjectName(u"lineEdit_163_usercookie")
        self.lineEdit_163_usercookie.setGeometry(QRect(210, 110, 541, 31))
        self.label = QLabel(self.tab_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 70, 321, 21))
        self.pushButton_delmusiccache = QPushButton(self.tab_4)
        self.pushButton_delmusiccache.setObjectName(u"pushButton_delmusiccache")
        self.pushButton_delmusiccache.setGeometry(QRect(100, 190, 191, 41))
        self.pushButton_delmusicimagecache = QPushButton(self.tab_4)
        self.pushButton_delmusicimagecache.setObjectName(u"pushButton_delmusicimagecache")
        self.pushButton_delmusicimagecache.setGeometry(QRect(310, 190, 191, 41))
        self.label_3 = QLabel(self.tab_4)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 150, 71, 31))
        self.pushButton_settings_addcookie = QPushButton(self.tab_4)
        self.pushButton_settings_addcookie.setObjectName(u"pushButton_settings_addcookie")
        self.pushButton_settings_addcookie.setGeometry(QRect(760, 110, 75, 31))
        self.comboBox_playmode_qssload = QComboBox(self.tab_4)
        self.comboBox_playmode_qssload.addItem("")
        self.comboBox_playmode_qssload.addItem("")
        self.comboBox_playmode_qssload.addItem("")
        self.comboBox_playmode_qssload.setObjectName(u"comboBox_playmode_qssload")
        self.comboBox_playmode_qssload.setGeometry(QRect(100, 280, 331, 41))
        self.comboBox_playmode_qssload.setStyleSheet(u"")
        self.label_4 = QLabel(self.tab_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(100, 240, 71, 21))
        self.pushButton_tab_music_settings = QPushButton(self.tab_4)
        self.pushButton_tab_music_settings.setObjectName(u"pushButton_tab_music_settings")
        self.pushButton_tab_music_settings.setGeometry(QRect(100, 20, 101, 31))
        self.pushButton_information = QPushButton(self.tab_4)
        self.pushButton_information.setObjectName(u"pushButton_information")
        self.pushButton_information.setGeometry(QRect(220, 20, 101, 31))
        self.tabWidget_2.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.pushButton_tab_music_settings_2 = QPushButton(self.tab_5)
        self.pushButton_tab_music_settings_2.setObjectName(u"pushButton_tab_music_settings_2")
        self.pushButton_tab_music_settings_2.setGeometry(QRect(100, 20, 101, 31))
        self.pushButton_information_2 = QPushButton(self.tab_5)
        self.pushButton_information_2.setObjectName(u"pushButton_information_2")
        self.pushButton_information_2.setGeometry(QRect(220, 20, 101, 31))
        self.label_5 = QLabel(self.tab_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(100, 70, 521, 21))
        self.label_6 = QLabel(self.tab_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(100, 535, 381, 21))
        self.label_7 = QLabel(self.tab_5)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(100, 112, 791, 31))
        self.label_picture_zycdzyj = QLabel(self.tab_5)
        self.label_picture_zycdzyj.setObjectName(u"label_picture_zycdzyj")
        self.label_picture_zycdzyj.setGeometry(QRect(100, 150, 131, 131))
        self.textEdit = QTextEdit(self.tab_5)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(320, 60, 451, 421))
        self.textEdit.setReadOnly(True)
        self.label_qq = QLabel(self.tab_5)
        self.label_qq.setObjectName(u"label_qq")
        self.label_qq.setGeometry(QRect(80, 300, 31, 31))
        self.label_9 = QLabel(self.tab_5)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(120, 300, 91, 31))
        self.tabWidget_2.addTab(self.tab_5, "")
        self.label_window_title_bar_2 = QLabel(self.tab_3)
        self.label_window_title_bar_2.setObjectName(u"label_window_title_bar_2")
        self.label_window_title_bar_2.setGeometry(QRect(0, 0, 1071, 31))
        self.label_close_window_3 = QLabel(self.tab_3)
        self.label_close_window_3.setObjectName(u"label_close_window_3")
        self.label_close_window_3.setGeometry(QRect(1110, 0, 21, 21))
        self.label_Minimize_3 = QLabel(self.tab_3)
        self.label_Minimize_3.setObjectName(u"label_Minimize_3")
        self.label_Minimize_3.setGeometry(QRect(1080, 0, 21, 21))
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Daybreak_music)

        self.tabWidget.setCurrentIndex(2)
        self.tabWidget_2.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Daybreak_music)
    # setupUi

    def retranslateUi(self, Daybreak_music):
        Daybreak_music.setWindowTitle(QCoreApplication.translate("Daybreak_music", u"daybreak_music&\u7834\u6653\u97f3\u4e50", None))
        ___qtablewidgetitem = self.listWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Daybreak_music", u"\u6b4c\u66f2\u540d", None));
        ___qtablewidgetitem1 = self.listWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Daybreak_music", u"\u4f5c\u8005", None));
        ___qtablewidgetitem2 = self.listWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Daybreak_music", u"\u64ad\u653e\u65f6\u957f", None));
        self.label_pictureload.setText(QCoreApplication.translate("Daybreak_music", u"\u56fe\u7247", None))
        self.pushButton.setText(QCoreApplication.translate("Daybreak_music", u"\u6253\u5f00\u6587\u4ef6\u5939", None))
        self.pushButton_nextsong.setText(QCoreApplication.translate("Daybreak_music", u"\u4e0b\u4e00\u9996", None))
        self.pushButton_beforesong.setText(QCoreApplication.translate("Daybreak_music", u"\u4e0a\u4e00\u9996", None))
        self.pushButton_playmusic.setText(QCoreApplication.translate("Daybreak_music", u"\u64ad\u653e", None))
        self.comboBox_playmode.setItemText(0, QCoreApplication.translate("Daybreak_music", u"\u987a\u5e8f\u64ad\u653e", None))
        self.comboBox_playmode.setItemText(1, QCoreApplication.translate("Daybreak_music", u"\u9006\u5e8f\u64ad\u653e", None))
        self.comboBox_playmode.setItemText(2, QCoreApplication.translate("Daybreak_music", u"\u5faa\u73af\u64ad\u653e", None))
        self.comboBox_playmode.setItemText(3, QCoreApplication.translate("Daybreak_music", u"\u968f\u673a\u64ad\u653e", None))

        self.checkBox_lrcshow.setText(QCoreApplication.translate("Daybreak_music", u"\u663e\u793a\u6b4c\u8bcd", None))
        self.label_musicprocesstext.setText(QCoreApplication.translate("Daybreak_music", u"\u6b4c\u66f2\u65f6\u95f4\u663e\u793a", None))
        self.label_songname.setText(QCoreApplication.translate("Daybreak_music", u"\u6b4c\u66f2\u540d", None))
        self.pushButton_localmusicsearch.setText(QCoreApplication.translate("Daybreak_music", u"\u672c\u5730\u97f3\u4e50", None))
        self.pushButton_internetmusicsearch.setText(QCoreApplication.translate("Daybreak_music", u"\u7f51\u7edc\u641c\u7d22", None))
        self.pushButton_settings.setText(QCoreApplication.translate("Daybreak_music", u"\u8bbe\u7f6e", None))
        self.label_window_title_bar.setText(QCoreApplication.translate("Daybreak_music", u"Daybreakmusic_\u7834\u6653\u97f3\u4e50", None))
        self.label_close_window.setText(QCoreApplication.translate("Daybreak_music", u"\u00d7", None))
        self.label_Minimize.setText(QCoreApplication.translate("Daybreak_music", u" \u2212", None))
        self.label_processbar_text_2.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Daybreak_music", u"Tab 1", None))
        self.pushButton_internetmusicsearch_2.setText(QCoreApplication.translate("Daybreak_music", u"\u7f51\u7edc\u641c\u7d22", None))
        self.pushButton_localmusicsearch_2.setText(QCoreApplication.translate("Daybreak_music", u"\u672c\u5730\u97f3\u4e50", None))
        self.lineEdit_163keywords.setText("")
        ___qtablewidgetitem3 = self.onlinesearch_tablewidget.horizontalHeaderItem(0)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Daybreak_music", u"\u6b4c\u66f2\u540d", None));
        ___qtablewidgetitem4 = self.onlinesearch_tablewidget.horizontalHeaderItem(1)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Daybreak_music", u"\u4f5c\u8005", None));
        self.pushButton_playmusic_2.setText(QCoreApplication.translate("Daybreak_music", u"\u64ad\u653e", None))
        self.pushButton_beforesong_2.setText(QCoreApplication.translate("Daybreak_music", u"\u4e0a\u4e00\u9996", None))
        self.pushButton_nextsong_2.setText(QCoreApplication.translate("Daybreak_music", u"\u4e0b\u4e00\u9996", None))
        self.label_musicprocesstext_2.setText(QCoreApplication.translate("Daybreak_music", u"\u6b4c\u66f2\u65f6\u95f4\u663e\u793a", None))
        self.label_pictureload_2.setText(QCoreApplication.translate("Daybreak_music", u"\u56fe\u7247", None))
        self.label_songname_2.setText(QCoreApplication.translate("Daybreak_music", u"\u6b4c\u66f2\u540d", None))
        self.comboBox_playmode_2.setItemText(0, QCoreApplication.translate("Daybreak_music", u"\u987a\u5e8f\u64ad\u653e", None))
        self.comboBox_playmode_2.setItemText(1, QCoreApplication.translate("Daybreak_music", u"\u9006\u5e8f\u64ad\u653e", None))
        self.comboBox_playmode_2.setItemText(2, QCoreApplication.translate("Daybreak_music", u"\u5faa\u73af\u64ad\u653e", None))
        self.comboBox_playmode_2.setItemText(3, QCoreApplication.translate("Daybreak_music", u"\u968f\u673a\u64ad\u653e", None))

        self.pushButton_settings_2.setText(QCoreApplication.translate("Daybreak_music", u"\u8bbe\u7f6e", None))
        self.pushButton_reloadonlinemusic.setText(QCoreApplication.translate("Daybreak_music", u"\u91cd\u65b0\u52a0\u8f7d", None))
        self.label_window_title_bar_3.setText(QCoreApplication.translate("Daybreak_music", u"Daybreakmusic_\u7834\u6653\u97f3\u4e50", None))
        self.label_close_window_2.setText(QCoreApplication.translate("Daybreak_music", u"\u00d7", None))
        self.label_Minimize_2.setText(QCoreApplication.translate("Daybreak_music", u" \u2212", None))
        self.label_processbar_text.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Daybreak_music", u"Tab 2", None))
        self.pushButton_localmusicsearch_3.setText(QCoreApplication.translate("Daybreak_music", u"\u672c\u5730\u97f3\u4e50", None))
        self.pushButton_internetmusicsearch_3.setText(QCoreApplication.translate("Daybreak_music", u"\u7f51\u7edc\u641c\u7d22", None))
        self.pushButton_settings_3.setText(QCoreApplication.translate("Daybreak_music", u"\u8bbe\u7f6e", None))
        self.label_2.setText(QCoreApplication.translate("Daybreak_music", u"\u7528\u6237cookie", None))
        self.label.setText(QCoreApplication.translate("Daybreak_music", u"\u7f51\u7edc\u97f3\u4e50\u8bbe\u7f6e", None))
        self.pushButton_delmusiccache.setText(QCoreApplication.translate("Daybreak_music", u"\u6e05\u9664\u6b4c\u66f2\u7f13\u5b58", None))
        self.pushButton_delmusicimagecache.setText(QCoreApplication.translate("Daybreak_music", u"\u6e05\u9664\u5c01\u9762\u7f13\u5b58", None))
        self.label_3.setText(QCoreApplication.translate("Daybreak_music", u"\u672c\u5730\u7f13\u5b58", None))
        self.pushButton_settings_addcookie.setText(QCoreApplication.translate("Daybreak_music", u"\u66f4\u6539", None))
        self.comboBox_playmode_qssload.setItemText(0, QCoreApplication.translate("Daybreak_music", u"\u9ed8\u8ba4\u4e3b\u9898", None))
        self.comboBox_playmode_qssload.setItemText(1, QCoreApplication.translate("Daybreak_music", u"\u6027\u80fd\u6a21\u5f0f", None))
        self.comboBox_playmode_qssload.setItemText(2, QCoreApplication.translate("Daybreak_music", u"\u9f99\u88d4\u00b7\u65e5\u7834\u6653", None))

        self.label_4.setText(QCoreApplication.translate("Daybreak_music", u"\u4e3b\u9898\u5207\u6362", None))
        self.pushButton_tab_music_settings.setText(QCoreApplication.translate("Daybreak_music", u"\u97f3\u4e50\u8bbe\u7f6e", None))
        self.pushButton_information.setText(QCoreApplication.translate("Daybreak_music", u"\u5173\u4e8e", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("Daybreak_music", u"Tab 1", None))
        self.pushButton_tab_music_settings_2.setText(QCoreApplication.translate("Daybreak_music", u"\u97f3\u4e50\u8bbe\u7f6e", None))
        self.pushButton_information_2.setText(QCoreApplication.translate("Daybreak_music", u"\u5173\u4e8e", None))
        self.label_5.setText(QCoreApplication.translate("Daybreak_music", u"\u7248\u672c:\u7834\u6653\u97f3\u4e50&Alpha 1.50", None))
        self.label_6.setText(QCoreApplication.translate("Daybreak_music", u"\u00a9 2026 \u7834\u6653\u97f3\u4e50\u5de5\u4f5c\u5ba4. \u4fdd\u7559\u6240\u6709\u6743\u5229", None))
        self.label_7.setText(QCoreApplication.translate("Daybreak_music", u"\u5f00\u53d1\u8005:zycdzyj", None))
        self.label_picture_zycdzyj.setText(QCoreApplication.translate("Daybreak_music", u"\u56fe\u7247", None))
        self.textEdit.setHtml(QCoreApplication.translate("Daybreak_music", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\" bgcolor=\"transparent\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; color:#ffffff;\">\u4e00\u4e2a\u65e0\u804a\u81f3\u6781\u7684\u9ad8\u4e2d\u5b66\u751f\u7f62\u4e86\u3002</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-weight:600; color:#4da6ff;\">Python \u7f16\u7a0b\u7231\u597d\u8005</span></p>\n"
"<p style=\" margin"
                        "-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-weight:600; color:#4da6ff;\">Python \u7f16\u7a0b\u5b66\u4e60\u8005</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-style:italic; color:#bd93f9;\">\u793e\u4f1a\u5de5\u7a0b\u5b66\u8005</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-style:italic; color:#bd93f9;\">INTP</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><spa"
                        "n style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-weight:600; color:#50fa7b;\">Minecraft \u7231\u597d\u8005</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-weight:600; color:#50fa7b;\">Minecraft \u6302\u5708/\u670d\u52a1\u5668\u73a9\u5bb6</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-weight:600; color:#50fa7b;\">\u5730\u72f1\u6f5c\u8005 2 \u73a9\u5bb6</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-w"
                        "eight:600; color:#50fa7b;\">soulmask</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; font-weight:600; color:#4da6ff;\">PySide6 \u5f00\u53d1\u8005</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; color:#ff79c6;\">\u79d1\u521b\u5927\u51a4\u79cd</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; color:#ffb86c;\">\u73a9\u673a</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; l"
                        "ine-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; color:#ff79c6;\">\u559c\u6b22\u6446\u70c2</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:150%;\"><span style=\" font-family:'Microsoft YaHei','SimHei','sans-serif'; font-size:14px; color:#ff79c6;\">\u559c\u6b22\u5973\u751f</span></p></body></html>", None))
        self.label_qq.setText(QCoreApplication.translate("Daybreak_music", u"QQ", None))
        self.label_9.setText(QCoreApplication.translate("Daybreak_music", u"3969204597", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), QCoreApplication.translate("Daybreak_music", u"Tab 2", None))
        self.label_window_title_bar_2.setText(QCoreApplication.translate("Daybreak_music", u"Daybreakmusic_\u7834\u6653\u97f3\u4e50", None))
        self.label_close_window_3.setText(QCoreApplication.translate("Daybreak_music", u"\u00d7", None))
        self.label_Minimize_3.setText(QCoreApplication.translate("Daybreak_music", u" \u2212", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Daybreak_music", u"\u9875", None))
    # retranslateUi

